conf: renews of /etc/grub.d/{01,10}

diff --git a/etc/sys/grub/00-grub-header b/etc/sys/grub/00-grub-header
--- a/etc/sys/grub/00-grub-header
+++ b/etc/sys/grub/00-grub-header
@@ -10,37 +10,49 @@ set -e
 prefix="/usr"
 exec_prefix="/usr"
 datarootdir="/usr/share"
-grub_lang=`echo $LANG | cut -d . -f 1`
-grubdir="`echo "/boot/grub" | sed 's,//*,/,g'`"
+
 quick_boot="1"
+grub_lang=$(echo ${LANG} | cut -d . -f 1)
+grubdir="$(echo "/boot/grub" | sed 's,//*,/,g')"
 
 export TEXTDOMAIN=grub
 export TEXTDOMAINDIR="${datarootdir}/locale"
 
-. "$pkgdatadir/grub-mkconfig_lib"
+# => ${pkgdatadir}/grub-mkconfig_lib
+# The helper library for grub-mkconfig
+if [ -f /usr/lib/grub/grub-mkconfig_lib ]; then
+  .  /usr/lib/grub/grub-mkconfig_lib
+elif [ -f /usr/share/grub/grub-mkconfig_lib ]; then
+  .  /usr/share/grub/grub-mkconfig_lib
+else
+  # no grub file, so we notify and exit gracefully
+  echo "ERROR: Can not find grub-mkconfig helper library file, exiting." >&2
+  exit 0
+fi
 
 # Do this as early as possible, since other commands might depend on it.
 # (e.g. the `loadfont' command might need lvm or raid modules)
 for i in ${GRUB_PRELOAD_MODULES} ; do
-  echo "insmod $i"
+  echo "insmod ${i}"
 done
 
-if [ "x${GRUB_DEFAULT}" = "x" ] ; then GRUB_DEFAULT=0 ; fi
-if [ "x${GRUB_DEFAULT}" = "xsaved" ] ; then GRUB_DEFAULT='${saved_entry}' ; fi
-if [ "x${GRUB_TIMEOUT}" = "x" ] ; then GRUB_TIMEOUT=5 ; fi
-if [ "x${GRUB_GFXMODE}" = "x" ] ; then GRUB_GFXMODE=auto ; fi
+if [ "x${GRUB_DEFAULT}" = "x" ]; then GRUB_DEFAULT=0; fi
+if [ "x${GRUB_DEFAULT}" = "xsaved" ]; then GRUB_DEFAULT='${saved_entry}'; fi
+if [ "x${GRUB_TIMEOUT}" = "x" ]; then GRUB_TIMEOUT=5; fi
+if [ "x${GRUB_GFXMODE}" = "x" ]; then GRUB_GFXMODE=auto; fi
 
-if [ "x${GRUB_DEFAULT_BUTTON}" = "x" ] ; then GRUB_DEFAULT_BUTTON="$GRUB_DEFAULT" ; fi
-if [ "x${GRUB_DEFAULT_BUTTON}" = "xsaved" ] ; then GRUB_DEFAULT_BUTTON='${saved_entry}' ; fi
-if [ "x${GRUB_TIMEOUT_BUTTON}" = "x" ] ; then GRUB_TIMEOUT_BUTTON="$GRUB_TIMEOUT" ; fi
+if [ "x${GRUB_DEFAULT_BUTTON}" = "x" ]; then GRUB_DEFAULT_BUTTON="$GRUB_DEFAULT";  fi
+if [ "x${GRUB_DEFAULT_BUTTON}" = "xsaved" ]; then GRUB_DEFAULT_BUTTON='${saved_entry}'; fi
+if [ "x${GRUB_TIMEOUT_BUTTON}" = "x" ]; then GRUB_TIMEOUT_BUTTON="$GRUB_TIMEOUT";  fi
 
 cat << EOF
-if [ -s \$prefix/grubenv ]; then
+if [ -s \${prefix}/grubenv ]; then
   set have_grubenv=true
   load_env
 fi
 EOF
-cat <<EOF
+
+cat << EOF
 if [ "\${initrdfail}" = 2 ]; then
    set initrdfail=
 elif [ "\${initrdfail}" = 1 ]; then
@@ -52,11 +64,12 @@ elif [ "\${initrdfail}" = 1 ]; then
    fi
 fi
 EOF
-if [ "x$GRUB_BUTTON_CMOS_ADDRESS" != "x" ]; then
-    cat <<EOF
-if cmostest $GRUB_BUTTON_CMOS_ADDRESS ; then
+
+if [ "x${GRUB_BUTTON_CMOS_ADDRESS}" != "x" ]; then
+  cat << EOF
+if cmostest ${GRUB_BUTTON_CMOS_ADDRESS}; then
    set default="${GRUB_DEFAULT_BUTTON}"
-elif [ "\${next_entry}" ] ; then
+elif [ "\${next_entry}" ]; then
    set default="\${next_entry}"
    set next_entry=
    save_env next_entry
@@ -66,8 +79,8 @@ else
 fi
 EOF
 else
-    cat <<EOF
-if [ "\${next_entry}" ] ; then
+  cat << EOF
+if [ "\${next_entry}" ]; then
    set default="\${next_entry}"
    set next_entry=
    save_env next_entry
@@ -77,7 +90,8 @@ else
 fi
 EOF
 fi
-cat <<EOF
+
+cat << EOF
 
 if [ x"\${feature_menuentry_id}" = xy ]; then
   menuentry_id_option="--id"
@@ -95,7 +109,7 @@ if [ "\${prev_saved_entry}" ]; then
   set boot_once=true
 fi
 
-function savedefault {
+function savedefault() {
   if [ -z "\${boot_once}" ]; then
     saved_entry="\${chosen}"
     save_env saved_entry
@@ -103,9 +117,10 @@ function savedefault {
 }
 EOF
 
-cat <<"EOF"
-function initrdfail {
-    if [ -n "${have_grubenv}" ]; then if [ -n "${partuuid}" ]; then
+cat << EOF
+function initrdfail() {
+  if [ -n "${have_grubenv}" ]; then
+    if [ -n "${partuuid}" ]; then
       if [ -z "${initrdfail}" ]; then
         set initrdfail=1
         if [ -n "${boot_once}" ]; then
@@ -114,23 +129,24 @@ function initrdfail {
         fi
       fi
       save_env initrdfail
-    fi; fi
+    fi
+  fi
 }
 EOF
 
-if [ "$quick_boot" = 1 ]; then
-    cat <<EOF
-function recordfail {
+if [ "${quick_boot}" = 1 ]; then
+  cat <<EOF
+function recordfail() {
   set recordfail=1
 EOF
 
-  check_writable () {
+  check_writable() {
     abstractions="$(grub-probe --target=abstraction "${grubdir}")"
-    for abstraction in $abstractions; do
-      case "$abstraction" in
+    for abstraction in ${abstractions}; do
+      case "${abstraction}" in
         diskfilter | lvm)
-          cat <<EOF
-  # GRUB lacks write support for $abstraction, so recordfail support is disabled.
+          cat << EOF
+  # GRUB lacks write support for ${abstraction}, so recordfail support is disabled.
 EOF
           return 1
           ;;
@@ -138,17 +154,21 @@ EOF
     done
 
     FS="$(grub-probe --target=fs "${grubdir}")"
-    case "$FS" in
+    case "${FS}" in
       btrfs | cpiofs | newc | odc | romfs | squash4 | tarfs | zfs)
-	cat <<EOF
-  # GRUB lacks write support for $FS, so recordfail support is disabled.
+        cat << EOF
+  # GRUB lacks write support for ${FS}, so recordfail support is disabled.
 EOF
-	return 1
-	;;
+        return 1
+        ;;
     esac
 
-    cat <<EOF
-  if [ -n "\${have_grubenv}" ]; then if [ -z "\${boot_once}" ]; then save_env recordfail; fi; fi
+    cat << EOF
+  if [ -n "\${have_grubenv}" ]; then
+    if [ -z "\${boot_once}" ]; then
+      save_env recordfail
+    fi
+  fi
 EOF
   }
 
@@ -156,23 +176,23 @@ EOF
     recordfail_broken=1
   fi
 
-  cat <<EOF
+  cat << EOF
 }
 EOF
 fi
 
-cat <<EOF
-function load_video {
+cat << EOF
+function load_video() {
 EOF
 if [ -n "${GRUB_VIDEO_BACKEND}" ]; then
-    cat <<EOF
+  cat << EOF
   insmod ${GRUB_VIDEO_BACKEND}
 EOF
 else
 # If all_video.mod isn't available load all modules available
 # with versions prior to introduction of all_video.mod
-cat <<EOF
-  if [ x\$feature_all_video_module = xy ]; then
+  cat << EOF
+  if [ x\${feature_all_video_module} = xy ]; then
     insmod all_video
   else
     insmod efi_gop
@@ -185,71 +205,67 @@ cat <<EOF
   fi
 EOF
 fi
-cat <<EOF
+cat << EOF
 }
 
 EOF
 
-serial=0;
-gfxterm=0;
+serial=0
+gfxterm=0
 for x in ${GRUB_TERMINAL_INPUT} ${GRUB_TERMINAL_OUTPUT}; do
-    if [ xserial = "x$x" ]; then
-	serial=1;
-    fi
-    if [ xgfxterm = "x$x" ]; then
-	gfxterm=1;
-    fi
+  if [ xserial = "x${x}" ]; then serial=1; fi
+  if [ xgfxterm = "x${x}" ]; then gfxterm=1; fi
 done
 
-if [ "x$serial" = x1 ]; then
-    if [ "x${GRUB_SERIAL_COMMAND}" = "x" ] ; then
-	grub_warn "$(gettext "Requested serial terminal but GRUB_SERIAL_COMMAND is unspecified. Default parameters will be used.")"
-	GRUB_SERIAL_COMMAND=serial
-    fi
-    echo "${GRUB_SERIAL_COMMAND}"
+if [ "x${serial}" = x1 ]; then
+  if [ "x${GRUB_SERIAL_COMMAND}" = "x" ]; then
+    grub_warn "$(gettext "Requested serial terminal but GRUB_SERIAL_COMMAND is unspecified. Default parameters will be used.")"
+    GRUB_SERIAL_COMMAND=serial
+  fi
+  echo "${GRUB_SERIAL_COMMAND}"
 fi
 
-if [ "x$gfxterm" = x1 ]; then
-    if [ -n "$GRUB_FONT" ] ; then
-       # Make the font accessible
-       prepare_grub_to_access_device `${grub_probe} --target=device "${GRUB_FONT}"`
+if [ "x${gfxterm}" = x1 ]; then
+  if [ -n "${GRUB_FONT}" ]; then
+    # Make the font accessible
+    prepare_grub_to_access_device $(${grub_probe} --target=device "${GRUB_FONT}")
     cat << EOF
-if loadfont `make_system_path_relative_to_its_root "${GRUB_FONT}"` ; then
+if loadfont $(make_system_path_relative_to_its_root "${GRUB_FONT}"); then
 EOF
-    else
-	for dir in "${pkgdatadir}" "`echo '/boot/grub' | sed "s,//*,/,g"`" /usr/share/grub ; do
-	    for basename in unicode unifont ascii; do
-		path="${dir}/${basename}.pf2"
-		if is_path_readable_by_grub "${path}" > /dev/null ; then
-		    font_path="${path}"
-		else
-		    continue
-		fi
-		break 2
-	    done
-	done
-	if [ -n "${font_path}" ] ; then
-    cat << EOF
-if [ x\$feature_default_font_path = xy ] ; then
-   font=unicode
+  else
+    for dir in "${pkgdatadir}" "$(echo '/boot/grub' | sed "s,//*,/,g")" /usr/share/grub; do
+      for basename in unicode unifont ascii; do
+        path="${dir}/${basename}.pf2"
+        if is_path_readable_by_grub "${path}" > /dev/null; then
+          font_path="${path}"
+        else
+          continue
+        fi
+        break 2
+      done
+    done
+    if [ -n "${font_path}" ]; then
+      cat << EOF
+if [ x\${feature_default_font_path} = xy ]; then
+  font=unicode
 else
 EOF
-                # Make the font accessible
-		prepare_grub_to_access_device `${grub_probe} --target=device "${font_path}"`
-    cat << EOF
-    font="`make_system_path_relative_to_its_root "${font_path}"`"
+      # Make the font accessible
+      prepare_grub_to_access_device $(${grub_probe} --target=device "${font_path}")
+      cat << EOF
+  font="$(make_system_path_relative_to_its_root "${font_path}")"
 fi
 
-if loadfont \$font ; then
+if loadfont \${font}; then
 EOF
-	    else
-    cat << EOF
-if loadfont unicode ; then
+    else
+      cat << EOF
+if loadfont unicode; then
 EOF
-	    fi
-	fi
+    fi
+  fi
 
-    cat << EOF
+  cat << EOF
   set gfxmode=${GRUB_GFXMODE}
   load_video
   insmod gfxterm
@@ -258,181 +274,178 @@ EOF
 # Gettext variables and module
 if [ "x${grub_lang}" != "xC" ] && [ "x${LANG}" != "xPOSIX" ] && [ "x${LANG}" != "x" ]; then
   cat << EOF
-  set locale_dir=\$prefix/locale
+  set locale_dir=\${prefix}/locale
   set lang=${grub_lang}
   insmod gettext
 EOF
 fi
 
-cat <<EOF
+cat << EOF
 fi
 EOF
 fi
 
 case x${GRUB_TERMINAL_INPUT} in
-  x)
-    # Just use the native terminal
-  ;;
+  x) # Just use the native terminal
+    ;;
   x*)
     cat << EOF
 terminal_input ${GRUB_TERMINAL_INPUT}
 EOF
-  ;;
+    ;;
 esac
 
 case x${GRUB_TERMINAL_OUTPUT} in
-  x)
-    # Just use the native terminal
-  ;;
+  x) # Just use the native terminal
+    ;;
   x*)
     cat << EOF
 terminal_output ${GRUB_TERMINAL_OUTPUT}
 EOF
-  ;;
+    ;;
 esac
 
-if [ "x$gfxterm" = x1 ]; then
-    if [ "x$GRUB_THEME" != x ] && [ -f "$GRUB_THEME" ] \
-	&& is_path_readable_by_grub "$GRUB_THEME"; then
-	gettext_printf "Found theme: %s\n" "$GRUB_THEME" >&2
-
-	prepare_grub_to_access_device `${grub_probe} --target=device "$GRUB_THEME"`
-	cat << EOF
+if [ "x${gfxterm}" = x1 ]; then
+  if [ "x${GRUB_THEME}" != x ] && [ -f "${GRUB_THEME}" ] && is_path_readable_by_grub "${GRUB_THEME}"; then
+    gettext_printf "Found theme: %s\n" "${GRUB_THEME}" >&2
+    prepare_grub_to_access_device $(${grub_probe} --target=device "${GRUB_THEME}")
+    cat << EOF
 insmod gfxmenu
 EOF
-	themedir="`dirname "$GRUB_THEME"`"
-	for x in "$themedir"/*.pf2 "$themedir"/f/*.pf2; do
-	    if [ -f "$x" ]; then
-		cat << EOF
-loadfont (\$root)`make_system_path_relative_to_its_root $x`
+    themedir="$(dirname "${GRUB_THEME}")"
+    for x in "${themedir}"/*.pf2 "${themedir}"/f/*.pf2; do
+      if [ -f "${x}" ]; then
+        cat << EOF
+loadfont (\${root})$(make_system_path_relative_to_its_root ${x})
 EOF
-	    fi
-	done
-	if [ x"`echo "$themedir"/*.jpg`" != x"$themedir/*.jpg" ] || [ x"`echo "$themedir"/*.jpeg`" != x"$themedir/*.jpeg" ]; then
-	    cat << EOF
+      fi
+    done
+
+    if [ x"$(echo "${themedir}"/*.jpg)" != x"${themedir}/*.jpg" ] || [ x"$(echo "${themedir}"/*.jpeg)" != x"${themedir}/*.jpeg" ]; then
+      cat << EOF
 insmod jpeg
 EOF
-	fi
-	if [ x"`echo "$themedir"/*.png`" != x"$themedir/*.png" ]; then
-	    cat << EOF
+    fi
+
+    if [ x"$(echo "${themedir}"/*.png)" != x"${themedir}/*.png" ]; then
+      cat << EOF
 insmod png
 EOF
-	fi
-	if [ x"`echo "$themedir"/*.tga`" != x"$themedir/*.tga" ]; then
-	    cat << EOF
+    fi
+
+    if [ x"$(echo "${themedir}"/*.tga)" != x"${themedir}/*.tga" ]; then
+      cat << EOF
 insmod tga
 EOF
-	fi
-	    
-	cat << EOF
-set theme=(\$root)`make_system_path_relative_to_its_root $GRUB_THEME`
+    fi
+
+    cat << EOF
+set theme=(\${root})$(make_system_path_relative_to_its_root ${GRUB_THEME})
 export theme
 EOF
-    elif [ "x$GRUB_BACKGROUND" != x ] && [ -f "$GRUB_BACKGROUND" ] \
-	    && is_path_readable_by_grub "$GRUB_BACKGROUND"; then
-	gettext_printf "Found background: %s\n" "$GRUB_BACKGROUND" >&2
-	case "$GRUB_BACKGROUND" in 
-	    *.png)         reader=png ;;
-	    *.tga)         reader=tga ;;
-	    *.jpg|*.jpeg)  reader=jpeg ;;
-	    *)             gettext "Unsupported image format" >&2; echo >&2; exit 1 ;;
-	esac
-	prepare_grub_to_access_device `${grub_probe} --target=device "$GRUB_BACKGROUND"`
-	cat << EOF
-insmod $reader
-background_image -m stretch `make_system_path_relative_to_its_root "$GRUB_BACKGROUND"`
+  elif [ "x${GRUB_BACKGROUND}" != x ] && [ -f "${GRUB_BACKGROUND}" ] && is_path_readable_by_grub "${GRUB_BACKGROUND}"; then
+    gettext_printf "Found background: %s\n" "${GRUB_BACKGROUND}" >&2
+    case "${GRUB_BACKGROUND}" in
+      *.png)         reader=png ;;
+      *.tga)         reader=tga ;;
+      *.jpg|*.jpeg)  reader=jpeg ;;
+      *) gettext "Unsupported image format" >&2; echo >&2; exit 1 ;;
+    esac
+    prepare_grub_to_access_device $(${grub_probe} --target=device "${GRUB_BACKGROUND}")
+    cat << EOF
+insmod ${reader}
+background_image -m stretch $(make_system_path_relative_to_its_root "${GRUB_BACKGROUND}")
 EOF
-    fi
+  fi
 fi
 
-make_timeout ()
-{
-    cat << EOF
-if [ "\${recordfail}" = 1 ] ; then
+make_timeout() {
+  cat << EOF
+if [ "\${recordfail}" = 1 ]; then
   set timeout=${GRUB_RECORDFAIL_TIMEOUT:-30}
 else
 EOF
-    if [ "x${3}" != "x" ] ; then
-	timeout="${2}"
-	style="${3}"
-    elif [ "x${1}" != "x" ] && \
-	 ([ "$quick_boot" = 1 ] || [ "x${1}" != "x0" ]) ; then
-	# Handle the deprecated GRUB_HIDDEN_TIMEOUT scheme.
-	timeout="${1}"
-	if [ "x${2}" != "x0" ] ; then
-	    grub_warn "$(gettext "Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.")"
-	fi
-	if [ "x${GRUB_HIDDEN_TIMEOUT_QUIET}" = "xtrue" ] ; then
-	    style="hidden"
-	    verbose=
-	else
-	    style="countdown"
-	    verbose=" --verbose"
-	fi
-    else
-	# No hidden timeout, so treat as GRUB_TIMEOUT_STYLE=menu
-	timeout="${2}"
-	style="menu"
+  if [ "x${3}" != "x" ]; then
+    timeout="${2}"
+    style="${3}"
+  elif [ "x${1}" != "x" ] && ([ "${quick_boot}" = 1 ] || [ "x${1}" != "x0" ]); then
+    # Handle the deprecated GRUB_HIDDEN_TIMEOUT scheme.
+    timeout="${1}"
+    if [ "x${2}" != "x0" ] ; then
+      grub_warn "$(gettext "Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.")"
     fi
-    cat << EOF
-  if [ x\$feature_timeout_style = xy ] ; then
+
+    if [ "x${GRUB_HIDDEN_TIMEOUT_QUIET}" = "xtrue" ] ; then
+      style="hidden"
+      verbose=
+    else
+      style="countdown"
+      verbose=" --verbose"
+    fi
+  else
+    # No hidden timeout, so treat as GRUB_TIMEOUT_STYLE=menu
+    timeout="${2}"
+    style="menu"
+  fi
+
+  cat << EOF
+  if [ x\${feature_timeout_style} = xy ]; then
     set timeout_style=${style}
     set timeout=${timeout}
 EOF
-    if [ "x${style}" = "xmenu" ] ; then
-	cat << EOF
-  # Fallback normal timeout code in case the timeout_style feature is
-  # unavailable.
+  if [ "x${style}" = "xmenu" ]; then
+    cat << EOF
+  # Fallback normal timeout code in case timeout_style feature is unavailable.
   else
     set timeout=${timeout}
 EOF
-    else
-	cat << EOF
-  # Fallback hidden-timeout code in case the timeout_style feature is
-  # unavailable.
-  elif sleep${verbose} --interruptible ${timeout} ; then
+  else
+    cat << EOF
+  # Fallback hidden-timeout code in case timeout_style feature is unavailable.
+  elif sleep${verbose} --interruptible ${timeout}; then
     set timeout=0
 EOF
-    fi
-    cat << EOF
+  fi
+
+  cat << EOF
   fi
 fi
 EOF
-if [ "$recordfail_broken" = 1 ]; then
-  cat << EOF
-if [ \$grub_platform = efi ]; then
+  if [ "${recordfail_broken}" = 1 ]; then
+    cat << EOF
+if [ \${grub_platform} = efi ]; then
   set timeout=${GRUB_RECORDFAIL_TIMEOUT:-30}
-  if [ x\$feature_timeout_style = xy ] ; then
+  if [ x\${feature_timeout_style} = xy ]; then
     set timeout_style=menu
   fi
 fi
 EOF
-fi
+  fi
 }
 
-if [ "x$GRUB_BUTTON_CMOS_ADDRESS" != "x" ]; then
-    cat <<EOF
-if cmostest $GRUB_BUTTON_CMOS_ADDRESS ; then
+if [ "x${GRUB_BUTTON_CMOS_ADDRESS}" != "x" ]; then
+  cat <<EOF
+if cmostest ${GRUB_BUTTON_CMOS_ADDRESS}; then
 EOF
-make_timeout "${GRUB_HIDDEN_TIMEOUT_BUTTON}" "${GRUB_TIMEOUT_BUTTON}" "${GRUB_TIMEOUT_STYLE_BUTTON}"
-echo else
-make_timeout "${GRUB_HIDDEN_TIMEOUT}" "${GRUB_TIMEOUT}" "${GRUB_TIMEOUT_STYLE}"
-echo fi
+  make_timeout "${GRUB_HIDDEN_TIMEOUT_BUTTON}" "${GRUB_TIMEOUT_BUTTON}" "${GRUB_TIMEOUT_STYLE_BUTTON}"
+  echo "else"
+  make_timeout "${GRUB_HIDDEN_TIMEOUT}" "${GRUB_TIMEOUT}" "${GRUB_TIMEOUT_STYLE}"
+  echo "fi"
 else
-make_timeout "${GRUB_HIDDEN_TIMEOUT}" "${GRUB_TIMEOUT}" "${GRUB_TIMEOUT_STYLE}"
+  make_timeout "${GRUB_HIDDEN_TIMEOUT}" "${GRUB_TIMEOUT}" "${GRUB_TIMEOUT_STYLE}"
 fi
 
-if [ "x$GRUB_BUTTON_CMOS_ADDRESS" != "x" ] && [ "x$GRUB_BUTTON_CMOS_CLEAN" = "xyes" ]; then
-    cat <<EOF
-cmosclean $GRUB_BUTTON_CMOS_ADDRESS
+if [ "x${GRUB_BUTTON_CMOS_ADDRESS}" != "x" ] && [ "x${GRUB_BUTTON_CMOS_CLEAN}" = "xyes" ]; then
+  cat << EOF
+cmosclean ${GRUB_BUTTON_CMOS_ADDRESS}
 EOF
 fi
 
 # Play an initial tune
-if [ "x${GRUB_INIT_TUNE}" != "x" ] ; then
+if [ "x${GRUB_INIT_TUNE}" != "x" ]; then
   echo "play ${GRUB_INIT_TUNE}"
 fi
 
-if [ "x${GRUB_BADRAM}" != "x" ] ; then
+if [ "x${GRUB_BADRAM}" != "x" ]; then
   echo "badram ${GRUB_BADRAM}"
 fi
diff --git a/etc/sys/grub/01-grub-theme b/etc/sys/grub/01-grub-theme
--- a/etc/sys/grub/01-grub-theme
+++ b/etc/sys/grub/01-grub-theme
@@ -7,181 +7,160 @@
 # Copy to /etc/grub.d/01-grub-theme
 set -e
 
-# Include the GRUB helper library for grub-mkconfig.
-. /usr/share/grub/grub-mkconfig_lib
+grub_errs() { echo "ERRS: $@" >&2; }
+grub_info() { echo "INFO: $@" >&2; }
+
+# => ${pkgdatadir}/grub-mkconfig_lib
+# The helper library for grub-mkconfig
+if [ -f /usr/lib/grub/grub-mkconfig_lib ]; then
+  .  /usr/lib/grub/grub-mkconfig_lib
+elif [ -f /usr/share/grub/grub-mkconfig_lib ]; then
+  .  /usr/share/grub/grub-mkconfig_lib
+else
+  # no grub file, so we notify and exit gracefully
+  grub_errs "Can not find grub-mkconfig helper library file, exiting."
+  exit 0
+fi
 
 # We want to work in /boot/grub/ only.
-test -d /boot/grub; cd /boot/grub
+test -d /boot/grub
+cd /boot/grub
 
 # Set the location of a possibly necessary cache file for the background image.
 # NOTE: This MUST BE A DOTFILE to avoid confusing it with user-defined images.
 BACKGROUND_CACHE=".background_cache"
 
-set_default_theme(){
-	case $GRUB_DISTRIBUTOR in
-		Tanglu|Ubuntu|Kubuntu)
-			# Set a monochromatic theme for Tanglu/Ubuntu.
-			echo "${1}set menu_color_normal=white/black"
-			echo "${1}set menu_color_highlight=black/light-gray"
-
-			if [ -e /usr/share/plymouth/themes/default.grub ]; then
-				sed "s/^/${1}/" /usr/share/plymouth/themes/default.grub
-			fi
-			# For plymouth backward compatibility. Can be removed
-			# after xenial.
-			if [ -e /lib/plymouth/themes/default.grub ]; then
-				sed "s/^/${1}/" /lib/plymouth/themes/default.grub
-			fi
-			;;
-		*)
-			# Set the traditional Debian blue theme.
-			echo "${1}set menu_color_normal=cyan/blue"
-			echo "${1}set menu_color_highlight=white/blue"
-			;;
-	esac
+set_default_theme() {
+  local indent_spaces="$1"
+  case ${GRUB_DISTRIBUTOR} in
+    *Arch* | *Debian* | *Ubuntu*)
+      # Set a monochromatic theme for Tanglu/Ubuntu.
+      echo "${indent_spaces}set menu_color_normal=white/black"
+      echo "${indent_spaces}set menu_color_highlight=black/light-gray"
+      ;;
+    *)
+      # Set the traditional Debian blue theme.
+      echo "${indent_spaces}set menu_color_normal=cyan/blue"
+      echo "${indent_spaces}set menu_color_highlight=white/blue"
+      ;;
+  esac
 }
 
-module_available(){
-	local module
-	for module in "${1}.mod" */"${1}.mod"; do
-		if [ -f "${module}" ]; then
-			return 0
-		fi
-	done
-	return 1
+module_available() {
+  local module
+  for module in "${1}.mod" */"${1}.mod"; do
+    if [ -f "${module}" ]; then
+      return 0
+    fi
+  done
+  return 1
 }
 
-set_background_image(){
-	# Step #1: Search all available output modes ...
-	local output
-	for output in ${GRUB_TERMINAL_OUTPUT}; do
-		if [ "x$output" = "xgfxterm" ]; then
-			break
-		fi
-	done
+# $1    path to picture, like "/path/to/x.png"
+# $2    color    normal, like "black/black"
+# $3    color highlight, like "magenta/black"
+set_background_image() {
+  # Step-1: Search all available output modes ...
+  local output
+  for output in ${GRUB_TERMINAL_OUTPUT}; do
+    if [ "x${output}" = "xgfxterm" ]; then
+      break
+    fi
+  done
 
-	# ... and check if we are able to display a background image at all.
-	if ! [ "x${output}" = "xgfxterm" ]; then
-		return 1
-	fi
+  # ... and check if we are able to display a background image at all.
+  if ! [ "x${output}" = "xgfxterm" ]; then
+    return 1
+  fi
 
-	# Step #2: Check if the specified background image exists.
-	if ! [ -f "${1}" ]; then
-		return 2
-	fi
+  # Step-2: Check if the specified background image exists.
+  if ! [ -f "${1}" ]; then
+    return 2
+  fi
 
-	# Step #3: Search the correct GRUB module for our background image.
-	local reader
-	case "${1}" in
-		*.jpg|*.JPG|*.jpeg|*.JPEG) reader="jpeg";;
-		*.png|*.PNG) reader="png";;
-		*.tga|*.TGA) reader="tga";;
-		*) return 3;; # Unknown image type.
-	esac
+  # Step-3: Search the correct GRUB module for our background image.
+  local reader
+  case "${1}" in
+    *.jpg | *.JPG | *.jpeg | *.JPEG) reader="jpeg" ;;
+    *.png | *.PNG) reader="png" ;;
+    *.tga | *.TGA) reader="tga" ;;
+    *) return 3 ;;
+  esac
 
-	# Step #4: Check if the necessary GRUB module is available.
-	if ! module_available "${reader}"; then
-		return 4
-	fi
+  # Step-4: Check if the necessary GRUB module is available.
+  if ! module_available "${reader}"; then
+    return 4
+  fi
 
-	# Step #5: Check if GRUB can read the background image directly.
-	# If so, we can remove the cache file (if any). Otherwise the background
-	# image needs to be cached under /boot/grub/.
-	if is_path_readable_by_grub "${1}"; then
-		rm --force "${BACKGROUND_CACHE}.jpeg" \
-			"${BACKGROUND_CACHE}.png" "${BACKGROUND_CACHE}.tga"
-	elif cp "${1}" "${BACKGROUND_CACHE}.${reader}"; then
-		set -- "${BACKGROUND_CACHE}.${reader}" "${2}" "${3}"
-	else
-		return 5
-	fi
+  # Step-5: Check if GRUB can read the background image directly.
+  # If so, we can remove the cache file (if any). Otherwise the
+  # background image needs to be cached under /boot/grub/.
+  if is_path_readable_by_grub "${1}"; then
+    rm --force "${BACKGROUND_CACHE}.jpeg" \
+               "${BACKGROUND_CACHE}.png" \
+               "${BACKGROUND_CACHE}.tga"
+  elif cp "${1}" "${BACKGROUND_CACHE}.${reader}"; then
+    set -- "${BACKGROUND_CACHE}.${reader}" "${2}" "${3}"
+  else
+    return 5
+  fi
 
-	# Step #6: Prepare GRUB to read the background image.
-	if ! prepare_grub_to_access_device "`${grub_probe} --target=device "${1}"`"; then
-		return 6
-	fi
+  # Step-6: Prepare GRUB to read the background image.
+  if ! prepare_grub_to_access_device "$(${grub_probe} --target=device "${1}")"; then
+    return 6
+  fi
 
-	# Step #7: Everything went fine, print out a message to stderr ...
-	echo "Found background image: ${1}" >&2
+  # Step-7: Everything went fine, print out a message to stderr ...
+  grub_info "Found background image: ${1}"
 
-	# ... and write our configuration snippet to stdout. Use the colors
-	# desktop-base specified. If we're using a user-defined background, use
-	# the default colors since we've got no idea how the image looks like.
-	# If loading the background image fails, use the default theme.
-	echo "insmod ${reader}"
-	echo "if background_image `make_system_path_relative_to_its_root "${1}"`; then"
-	if [ -n "${2}" ]; then
-		echo "  set color_normal=${2}"
-	fi
-	if [ -n "${3}" ]; then
-		echo "  set color_highlight=${3}"
-	fi
-	if [ -z "${2}" ] && [ -z "${3}" ]; then
-		echo "  true"
-	fi
-	echo "else"
-	set_default_theme "  "
-	echo "fi"
+  # ... and write our configuration snippet to stdout. Use the colors
+  # desktop-base specified. If we're using a user-defined background, use
+  # the default colors since we've got no idea how the image looks like.
+  # If loading the background image fails, use the default theme.
+  echo "insmod ${reader}"
+  echo "if background_image $(make_system_path_relative_to_its_root "${1}"); then"
+  if [ -n "${2}" ]; then
+    echo "  set color_normal=${2}"
+  fi
+  if [ -n "${3}" ]; then
+    echo "  set color_highlight=${3}"
+  fi
+  if [ -z "${2}" ] && [ -z "${3}" ]; then
+    echo "  true"
+  fi
+  echo "else"
+  set_default_theme "  "
+  echo "fi"
 }
 
-# Earlier versions of grub-pc copied the default background image to /boot/grub
-# during postinst. Remove those obsolete images if they haven't been touched by
-# the user. They are still available under /usr/share/images/desktop-base/ if
-# desktop-base is installed.
+# Remove obsolete /boot/grub/* images, which are copied by earlier version grub.
 while read checksum background; do
-	if [ -f "${background}" ] && [ "x`sha1sum "${background}"`" = "x${checksum}  ${background}" ]; then
-		echo "Removing old background image: ${background}" >&2
-		rm "${background}"
-	fi
-done <<EOF
-648ee65dd0c157a69b019a5372cbcfea4fc754a5  debian-blueish-wallpaper-640x480.png
-0431e97a6c661084c59676c4baeeb8c2f602edb8  debian-blueish-wallpaper-640x480.png
-968ecf6696c5638cfe80e8e70aba239526270864  debian-blueish-wallpaper-640x480.tga
-11143e8c92a073401de0b0fd42d0c052af4ccd9b  moreblue-orbit-grub.png
-d00d5e505ab63f2d53fa880bfac447e2d3bb197c  moreblue-orbit-grub.png
-f5b12c1009ec0a3b029185f6b66cd0d7e5611019  moreblue-orbit-grub.png
+  if [ -f "${background}" ] && [ "x$(sha1sum "${background}")" = "x${checksum}  ${background}" ]; then
+    grub_info "Remove old background image: ${background}"
+    rm "${background}"
+  fi
+done << EOF
+648ee65dd0c157a69b019a5372cbcfea4fc754a5  debian-wallpaper-640x480.png
+11143e8c92a073401de0b0fd42d0c052af4ccd9b  moreblue-wallpaper-64x64.png
 EOF
 
-# Include the configuration of desktop-base if available.
-if [ -f "/usr/share/desktop-base/grub_background.sh" ]; then
-	. "/usr/share/desktop-base/grub_background.sh"
+# First check whether user has specified a background image explicitly.
+if [ -n "${GRUB_BACKGROUND+x}" ]; then
+  set_background_image "${GRUB_BACKGROUND}" || set_default_theme
+  exit 0
 fi
 
-# First check whether the user has specified a background image explicitly.
-# If so, try to use it. Don't try the other possibilities in that case
-# (#608263).
-if [ -n "${GRUB_BACKGROUND+x}" ]; then
-	set_background_image "${GRUB_BACKGROUND}" || set_default_theme
-	exit 0
+# Next try to use the background image and colors specified by the user.
+if set_background_image "${GRUB_WALLPAPER}" "${GRUB_COLOR_NORMAL}" "${GRUB_COLOR_HIGHLIGHT}"; then
+  exit 0
 fi
 
 # Next search for pictures the user put into /boot/grub/ and use the first one.
 for background in *.jpg *.JPG *.jpeg *.JPEG *.png *.PNG *.tga *.TGA; do
-	if set_background_image "${background}"; then
-		exit 0
-	fi
+  if set_background_image "${background}"; then
+    exit 0
+  fi
 done
-
-# Next try to use the background image and colors specified by desktop-base.
-if set_background_image "${WALLPAPER}" "${COLOR_NORMAL}" "${COLOR_HIGHLIGHT}"; then
-	exit 0
-fi
-
-# If we haven't found a background image yet, use the default from desktop-base.
-case $GRUB_DISTRIBUTOR in
-	Ubuntu|Kubuntu)
-		;;
-	Tanglu)
-		if set_background_image "/usr/share/images/grub/grub.png"; then
-			exit 0
-		fi
-		;;
-	*)
-		if set_background_image "/usr/share/images/desktop-base/desktop-grub.png"; then
-			exit 0
-		fi
-		;;
-esac
 
 # Finally, if all of the above fails, use the default theme.
 set_default_theme
